In [19]:
import turicreate
import numpy as np
import json
import string

In [20]:
# loading the data
products = turicreate.SFrame('amazon_baby_subset.sframe')

In [21]:
products['name'].head()
products.shape

(53072, 4)

In [22]:
products.tail()

Columns:
	name	str
	review	str
	rating	float
	sentiment	int

Rows: 10

Data:
+-------------------------------+-------------------------------+--------+-----------+
|              name             |             review            | rating | sentiment |
+-------------------------------+-------------------------------+--------+-----------+
| Vandot 2 in1 Accessory Set... | Cute but cheaply made.. Th... |  2.0   |     -1    |
| Umai Authentic Hazelwood a... |     Made no difference :/     |  1.0   |     -1    |
| 360 Degree Rotating Cover ... | Be careful it stains your ... |  1.0   |     -1    |
| Summer Infant Pop 'n Play ... | Good idea but too dangerou... |  2.0   |     -1    |
| Freeens Cool Seat Liner Br... | It doesn't stay input. My ... |  1.0   |     -1    |
| Samsung Baby Care Washer, ... | My infant goes to a really... |  1.0   |     -1    |
| Mud Pie Milestone Stickers... | Pretty please open and ins... |  1.0   |     -1    |
| Best BIB for Baby - Soft B... | Great 5-Star Product but A... |  1.0   |     -1    |
| Bouncy&reg; Inflatable Rea... | When I received the item m... |  2.0   |     -1    |
| Maxboost iPhone 5S/5 Case ... | I got this case in the mai... |  2.0   |     -1    |
+-------------------------------+-------------------------------+--------+-----------+
[10 rows x 4 columns]

In [24]:
with open('important_words.json','r') as f:
    important_words = json.load(f)

In [25]:
# removing the punctuations
def remove_punch(t):
    translater = t.maketrans('','',string.punctuation)
    return t.translate(translater)

In [26]:
products['cl_review'] = products['review'].apply(remove_punch)

In [27]:
products

Columns:
	name	str
	review	str
	rating	float
	sentiment	int
	cl_review	str

Rows: 53072

Data:
+-------------------------------+-------------------------------+--------+-----------+
|              name             |             review            | rating | sentiment |
+-------------------------------+-------------------------------+--------+-----------+
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |     1     |
| Nature's Lullabies Second ... | We wanted to get something... |  5.0   |     1     |
| Nature's Lullabies Second ... | My daughter had her 1st ba... |  5.0   |     1     |
|  Lamaze Peekaboo, I Love You  | One of baby's first and fa... |  4.0   |     1     |
| SoftPlay Peek-A-Boo Where'... | Very cute interactive book... |  5.0   |     1     |
|   Our Baby Girl Memory Book   | Beautiful book, I love it ... |  5.0   |     1     |
| Hunnt&reg; Falling Flowers... | Try this out for a spring ... |  5.0   |     1     |
| Blessed By Pope Benedict X... | very nice Divine Mercy Pen... |  5.0   |     1     |
| Cloth Diaper Pins Stainles... | We bought the pins as my 6... |  4.0   |     1     |
| Cloth Diaper Pins Stainles... | It has been many years sin... |  5.0   |     1     |
+-------------------------------+-------------------------------+--------+-----------+
+-------------------------------+
|           cl_review           |
+-------------------------------+
| All of my kids have cried ... |
| We wanted to get something... |
| My daughter had her 1st ba... |
| One of babys first and fav... |
| Very cute interactive book... |
| Beautiful book I love it t... |
| Try this out for a spring ... |
| very nice Divine Mercy Pen... |
| We bought the pins as my 6... |
| It has been many years sin... |
+-------------------------------+
[53072 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [28]:
for w in important_words:
    products[w] = products['cl_review'].apply(lambda s:s.split().count(w))

In [29]:
products

Columns:
	name	str
	review	str
	rating	float
	sentiment	int
	cl_review	str
	baby	int
	one	int
	great	int
	love	int
	use	int
	would	int
	like	int
	easy	int
	little	int
	seat	int
	old	int
	well	int
	get	int
	also	int
	really	int
	son	int
	time	int
	bought	int
	product	int
	good	int
	daughter	int
	much	int
	loves	int
	stroller	int
	put	int
	months	int
	car	int
	still	int
	back	int
	used	int
	recommend	int
	first	int
	even	int
	perfect	int
	nice	int
	bag	int
	two	int
	using	int
	got	int
	fit	int
	around	int
	diaper	int
	enough	int
	month	int
	price	int
	go	int
	could	int
	soft	int
	since	int
	buy	int
	room	int
	works	int
	made	int
	child	int
	keep	int
	size	int
	small	int
	need	int
	year	int
	big	int
	make	int
	take	int
	easily	int
	think	int
	crib	int
	clean	int
	way	int
	quality	int
	thing	int
	better	int
	without	int
	set	int
	new	int
	every	int
	cute	int
	best	int
	bottles	int
	work	int
	purchased	int
	right	int
	lot	int
	side	int
	happy	int
	comfortable	int
	toy	int
	able	int
	kids	int
	bit	int
	night	int
	long	int
	fits	int
	see	int
	us	int
	another	int
	play	int
	day	int
	money	int
	monitor	int
	tried	int
	thought	int
	never	int
	item	int
	hard	int
	plastic	int
	however	int
	disappointed	int
	reviews	int
	something	int
	going	int
	pump	int
	bottle	int
	cup	int
	waste	int
	return	int
	amazon	int
	different	int
	top	int
	want	int
	problem	int
	know	int
	water	int
	try	int
	received	int
	sure	int
	times	int
	chair	int
	find	int
	hold	int
	gate	int
	open	int
	bottom	int
	away	int
	actually	int
	cheap	int
	worked	int
	getting	int
	ordered	int
	came	int
	milk	int
	bad	int
	part	int
	worth	int
	found	int
	cover	int
	many	int
	design	int
	looking	int
	weeks	int
	say	int
	wanted	int
	look	int
	place	int
	purchase	int
	looks	int
	second	int
	piece	int
	box	int
	pretty	int
	trying	int
	difficult	int
	together	int
	though	int
	give	int
	started	int
	anything	int
	last	int
	company	int
	come	int
	returned	int
	maybe	int
	took	int
	broke	int
	makes	int
	stay	int
	instead	int
	idea	int
	head	int
	said	int
	less	int
	went	int
	working	int
	high	int
	unit	int
	seems	int
	picture	int
	completely	int
	wish	int
	buying	int
	babies	int
	won	int
	tub	int
	almost	int
	either	int

Rows: 53072

Data:
+-------------------------------+-------------------------------+--------+-----------+
|              name             |             review            | rating | sentiment |
+-------------------------------+-------------------------------+--------+-----------+
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |     1     |
| Nature's Lullabies Second ... | We wanted to get something... |  5.0   |     1     |
| Nature's Lullabies Second ... | My daughter had her 1st ba... |  5.0   |     1     |
|  Lamaze Peekaboo, I Love You  | One of baby's first and fa... |  4.0   |     1     |
| SoftPlay Peek-A-Boo Where'... | Very cute interactive book... |  5.0   |     1     |
|   Our Baby Girl Memory Book   | Beautiful book, I love it ... |  5.0   |     1     |
| Hunnt&reg; Falling Flowers... | Try this out for a spring ... |  5.0   |     1     |
| Blessed By Pope Benedict X... | very nice Divine Mercy Pen... |  5.0   |     1     |
| Cloth Diaper Pins Stainles... | We bought the pins as my 6... |  4.0   |     1     |
| Cloth Diaper Pins Stainles... | It has been many years sin... |  5.0   |     1     |
+-------------------------------+-------------------------------+--------+-----------+
+-------------------------------+------+-----+-------+------+-----+-------+------+
|           cl_review           | baby | one | great | love | use | would | like |
+-------------------------------+------+-----+-------+------+-----+-------+------+
| All of my kids have cried ... |  0   |  0  |   1   |  0   |  0  |   0   |  0   |
| We wanted to get something... |  0   |  0  |   0   |  0   |  0  |   0   |  0   |
| My daughter had her 1st ba... |  1   |  0  |   0   |  0   |  0  |   0   |  0   |
| One of babys first and fav... |  0   |  0  |   0   |  0   |  0  

In [31]:
products['con_perfect'] = products['perfect'].apply(lambda c:1 if c >= 1 else 0)

In [58]:
products['con_perfect'].sum()

2955

2955

In [60]:
# constructing the numpy array

In [61]:
def get_numpy_data(data_sframe, features, label):
    data_sframe['intercept'] = 1
    features = ['intercept'] + features
    features_sframe = data_sframe[features]
    feature_matrix = features_sframe.to_numpy()
    label_sarray = data_sframe[label]
    label_array = label_sarray.to_numpy()
    return(feature_matrix, label_array)

In [62]:
feature_matrix, sentiment = get_numpy_data(products, important_words, 'sentiment') 

In [63]:
feature_matrix.shape

(53072, 194)

In [64]:
feature_matrix

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [65]:
len(important_words)

193

In [68]:
len(sentiment)

53072

In [69]:
c = np.arange(194)

In [72]:
np.dot(feature_matrix,c)

array([1017,  696,  499, ..., 1038, 2085, 1474])

In [73]:
np.dot(feature_matrix,np.transpose(c))

array([1017,  696,  499, ..., 1038, 2085, 1474])

In [74]:
d = 1/(1+np.exp(-np.dot(feature_matrix,np.transpose(c))))

In [75]:
d

array([1., 1., 1., ..., 1., 1., 1.])

In [76]:
def predict_probability(feature_matrix, coefficients):
    # Take dot product of feature_matrix and coefficients 
    p = np.dot(feature_matrix, coefficients)
    # YOUR CODE HERE
    
    
    # Compute P(y_i = +1 | x_i, w) using the link function
    # YOUR CODE HERE
    predictions = 1/(1+np.exp(-p))
    
    # return predictions
    return predictions

In [77]:
dummy_feature_matrix = np.array([[1.,2.,3.], [1.,-1.,-1]])
dummy_coefficients = np.array([1., 3., -1.])

correct_scores      = np.array( [ 1.*1. + 2.*3. + 3.*(-1.),          1.*1. + (-1.)*3. + (-1.)*(-1.) ] )
correct_predictions = np.array( [ 1./(1+np.exp(-correct_scores[0])), 1./(1+np.exp(-correct_scores[1])) ] )

print('The following outputs must match ')
print('------------------------------------------------')
print('correct_predictions           =', correct_predictions)
print('output of predict_probability =', predict_probability(dummy_feature_matrix, dummy_coefficients))

The following outputs must match 
------------------------------------------------
correct_predictions           = [0.98201379 0.26894142]
output of predict_probability = [0.98201379 0.26894142]


In [78]:
def feature_derivative(errors, feature):     
    # Compute the dot product of errors and feature
    derivative = np.dot(errors,feature)
    
    # Return the derivative
    return derivative

In [79]:
def compute_log_likelihood(feature_matrix, sentiment, coefficients):
    indicator = (sentiment==+1)
    scores = np.dot(feature_matrix, coefficients)
    logexp = np.log(1. + np.exp(-scores))
    
    # Simple check to prevent overflow
    mask = np.isinf(logexp)
    logexp[mask] = -scores[mask]
    
    lp = np.sum((indicator-1)*scores - logexp)
    return lp

In [80]:
dummy_feature_matrix = np.array([[1.,2.,3.], [1.,-1.,-1]])
dummy_coefficients = np.array([1., 3., -1.])
dummy_sentiment = np.array([-1, 1])

correct_indicators  = np.array( [ -1==+1,                                       1==+1 ] )
correct_scores      = np.array( [ 1.*1. + 2.*3. + 3.*(-1.),                     1.*1. + (-1.)*3. + (-1.)*(-1.) ] )
correct_first_term  = np.array( [ (correct_indicators[0]-1)*correct_scores[0],  (correct_indicators[1]-1)*correct_scores[1] ] )
correct_second_term = np.array( [ np.log(1. + np.exp(-correct_scores[0])),      np.log(1. + np.exp(-correct_scores[1])) ] )

correct_ll          =      sum( [ correct_first_term[0]-correct_second_term[0], correct_first_term[1]-correct_second_term[1] ] ) 

print('The following outputs must match ')
print('------------------------------------------------')
print('correct_log_likelihood           =', correct_ll)
print('output of compute_log_likelihood =', compute_log_likelihood(dummy_feature_matrix, dummy_sentiment, dummy_coefficients))

The following outputs must match 
------------------------------------------------
correct_log_likelihood           = -5.331411615436032
output of compute_log_likelihood = -5.331411615436032


In [ ]:
rom math import sqrt

def logistic_regression(feature_matrix, sentiment, initial_coefficients, step_size, max_iter):
    coefficients = np.array(initial_coefficients) # make sure it's a numpy array
    for itr in range(max_iter):

        # Predict P(y_i = +1|x_i,w) using your predict_probability() function
        # YOUR CODE HERE
        predictions = predict_probability(feature_matrix, coefficients)
        
        # Compute indicator value for (y_i = +1)
        indicator = (sentiment==+1)
        
        # Compute the errors as indicator - predictions
        errors = indicator - predictions
        for j in range(len(coefficients)): # loop over each coefficient
            
            # Recall that feature_matrix[:,j] is the feature column associated with coefficients[j].
            # Compute the derivative for coefficients[j]. Save it in a variable called derivative
            # YOUR CODE HERE
            derivative = feature_derivative(errors, feature)
            # add the step size times the derivative to the current coefficient
            ## YOUR CODE HERE
            ...
        
        # Checking whether log likelihood is increasing
        if itr <= 15 or (itr <= 100 and itr % 10 == 0) or (itr <= 1000 and itr % 100 == 0) \
        or (itr <= 10000 and itr % 1000 == 0) or itr % 10000 == 0:
            lp = compute_log_likelihood(feature_matrix, sentiment, coefficients)
            print('iteration %*d: log likelihood of observed labels = %.8f' % \
                (int(np.ceil(np.log10(max_iter))), itr, lp))
    return coefficients